OMP_NUM_THREADS = 16
MKL_NUM_THREADS = 1
PYSCF_MAX_MEMORY = 491520
TMPDIR = /central/scratch/yangjunjie//nio-dzvp-444/47154646/
PYSCF_TMPDIR = /central/scratch/yangjunjie//nio-dzvp-444/47154646/

/home/junjiey/anaconda3/envs/fftisdf/bin/python
2.8.0
1.13.1
1.26.4
Traceback (most recent call last):
  File "/central/home/junjiey/work/fftisdf-benchmark-new/test/nio-dzvp-444-mpi/fft_isdf.py", line 2, in <module>
Traceback (most recent call last):
  File "/central/home/junjiey/work/fftisdf-benchmark-new/test/nio-dzvp-444-mpi/fft_isdf.py", line 2, in <module>
Traceback (most recent call last):
  File "/central/home/junjiey/work/fftisdf-benchmark-new/test/nio-dzvp-444-mpi/fft_isdf.py", line 2, in <module>
Traceback (most recent call last):
  File "/central/home/junjiey/work/fftisdf-benchmark-new/test/nio-dzvp-444-mpi/fft_isdf.py", line 2, in <module>
    from mpi4py import MPI
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
    from mpi4py import MPI
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
    from mpi4py import MPI
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
    from mpi4py import MPI
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
srun: error: hpc-35-01: tasks 0-3: Exited with exit code 1
